# Generated by Django 3.1.7 on 2021-03-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreuServeiAlRefugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio_Servei', models.TextField()),
                ('preu_Servei', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Refugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Refugi', models.CharField(max_length=70)),
                ('coordenades', models.CharField(max_length=100)),
                ('descripcio_Refugi', models.TextField()),
                ('valoracio_Refugi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Servei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Servei', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Ressenya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Autor', models.CharField(max_length=70)),
                ('titol_Ressenya', models.CharField(max_length=20)),
                ('text_Ressenya', models.TextField()),
                ('valoracio', models.IntegerField()),
                ('data_Creacio', models.DateTimeField(auto_now_add=True)),
                ('refugi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefugisCAT.refugi')),
            ],
        ),
        migrations.AddField(
            model_name='refugi',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='serveis', through='RefugisCAT.PreuServeiAlRefugi', to='RefugisCAT.Servei'),
        ),
        migrations.AddField(
            model_name='preuserveialrefugi',
            name='refugi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefugisCAT.refugi'),
        ),
        migrations.AddField(
            model_name='preuserveialrefugi',
            name='servei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefugisCAT.servei'),
        ),
    ]
