# Generated by Django 3.1.7 on 2021-03-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefugisCAT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugi',
            name='imatge',
            field=models.FilePathField(default='SENSE IMATGE', path='/static/img'),
            preserve_default=False,
        ),
    ]
