# Generated by Django 3.0.4 on 2021-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefugisCAT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugi',
            name='serveis',
            field=models.ManyToManyField(blank=True, related_name='serveis', to='RefugisCAT.Servei'),
        ),
    ]
