# Generated by Django 3.1.7 on 2021-03-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RefugisCAT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugi',
            name='serveis',
        ),
        migrations.RemoveField(
            model_name='servei',
            name='descripcio_Servei',
        ),
        migrations.RemoveField(
            model_name='servei',
            name='preu_Servei',
        ),
        migrations.CreateModel(
            name='PreuServeiAlRefugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio_Servei', models.TextField()),
                ('preu_Servei', models.FloatField()),
                ('refugi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefugisCAT.refugi')),
                ('servei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefugisCAT.servei')),
            ],
        ),
        migrations.AddField(
            model_name='refugi',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='serveis', through='RefugisCAT.PreuServeiAlRefugi', to='RefugisCAT.Servei'),
        ),
    ]
