# Generated by Django 3.1.7 on 2021-03-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefugisCAT', '0002_refugi_imatge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugi',
            name='imatge',
            field=models.CharField(max_length=100),
        ),
    ]
