# Generated by Django 3.1.7 on 2021-03-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefugisCAT', '0002_auto_20210317_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressenya',
            name='titol_Ressenya',
            field=models.CharField(default='Des del meu punt de vista', max_length=20),
            preserve_default=False,
        ),
    ]
