# Generated by Django 3.1.7 on 2021-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefugisCAT', '0003_auto_20210320_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='servei',
            name='imatge',
            field=models.CharField(default='img/no_resultats.jpeg', max_length=100),
            preserve_default=False,
        ),
    ]
