# Generated by Django 3.1.7 on 2021-03-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RefugisCAT', '0004_servei_imatge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refugi',
            old_name='members',
            new_name='serveis',
        ),
    ]
